-- Controlled tag vocabulary from neesh-niche-page-intros-v2.md, replacing
-- the starter set. No titles have been imported yet, so the old rows carry
-- no references. Long intros (verified) load into intro_md for the five
-- niches expected to clear the 5-title threshold; short intros load for the
-- hold niches so their pages are ready when they cross it.

delete from directory_title_tags;
delete from directory_tags;

insert into directory_tags (slug, name, intro_md) values
('food-drink', 'Food & Drink', $md$Food is the deepest category in independent print, and it isn't close. The reason is that food writing outgrew the recipe. The best titles now use a plate as a way into history, labor, and money. Cake Zine runs essays, fiction, and recipes built around sweets, one theme per issue. Eaten covers food history three times a year, mostly through archival material. Noble Rot has been writing about wine out of London since 2013 without the reverence, and Standart does specialty coffee out of Prague. Almost none of it reaches a newsstand, which is why the good ones sell out and stay sold out.$md$),
('travel', 'Travel', $md$Independent travel print survived the collapse of the guidebook by refusing to do the guidebook's job. These titles aren't telling you where to eat. Flaneur takes a single street per issue and moves the team there for months to make it. Drift builds each issue around one city's coffee culture and has run ad-free since it started. Sidetracked publishes expedition and adventure writing three times a year at a length no website would commission. The format works because a place takes more room than a listicle allows, and because a magazine about somewhere else is the correct object to leave in a hotel lobby.$md$),
('sport-outdoors', 'Sport & Outdoors', $md$Sport print got good the moment it stopped chasing scores. Nobody needs a magazine for results, so the independents went where the internet doesn't. Racquet covers the art, ideas, and style around tennis, quarterly, because there was almost no narrative journalism in the sport. Victory Journal runs sport and culture at a format large enough to take over a table. Shukyu covers global football from Tokyo, in Japanese with English throughout. Mountain Gazette has been documenting mountain life since 1966 and prints at 11x17. Gyms, climbing walls, and run clubs are full of people who would read all of this and mostly can't find it.$md$),
('design-architecture', 'Design & Architecture', $md$Design magazines have the easiest job in print and the hardest standard, because the object has to be as considered as the subject. The good ones clear it. MacGuffin builds every biannual issue around one ordinary object, a bed, a window, a rope, and calls the beat the life of things. Eye has been the reference for graphic design since 1990. Safar works between Arabic and Latin type out of Beirut, printing half the magazine in each language. Kinfolk and Cereal set a visual register that a thousand imitators are still working through. These are the titles that quietly leave studios in someone's bag.$md$),
('art-literature', 'Art & Literature', $md$Literary print is the oldest independent format and the one that keeps proving the model works, because readers who want essays and fiction actually want to hold them. Deem Journal comes out of Los Angeles twice a year treating design as a social practice, built around long interviews with people the design industry usually talks past. Dumbo Feather runs long-form conversations at a length the internet stopped allowing. Somesuch Editions publishes fiction and essays with the production values of an art book. These are slow objects for slow reading, and they hold a shelf longer than anything else in the index.$md$),
('fashion', 'Fashion', $md$Fashion print splits between the ones covering the industry and the ones interrogating it. Vestoj runs closer to academic than editorial, The Skirt Chronicles reads like correspondence between friends who happen to have taste, and Mildew covers vintage and secondhand as a practice rather than a trend.$md$),
('music', 'Music', $md$Music print goes deeper than any streaming service's editorial, because it's written by people embedded in scenes rather than assigned to them. zweikommasieben has been documenting experimental and electronic music out of Switzerland since 2012, and Heartbeat sits where music, sound, and art overlap.$md$),
('politics-journalism', 'Politics & Journalism', $md$Slow political print exists because the news cycle broke and somebody had to write the version that holds up a year later. The Baffler has run cultural and economic criticism since 1988, The Drift publishes essays and criticism from writers outside the media consensus, and Delayed Gratification only covers a story once the outcome is known.$md$),
('film-photography', 'Film & Photography', $md$Film criticism moved online and mostly got worse, which left an opening for print that treats a film as an object worth designing around. Little White Lies commissions original illustration for its lead reviews and has been doing it since 2005.$md$),
('nature', 'Nature', $md$Nature print has moved past landscape photography into something closer to field research with a design budget. Mushroom People covers mycology and the culture around it, and Catnip does cats seriously enough to be funny.$md$),
('cannabis-wellness', 'Cannabis & Wellness', $md$Cannabis print grew up alongside legalization and mostly skipped the stoner register entirely. Broccoli is women-led and reads like an art magazine that happens to be about weed, and Gossamer covers cannabis through wellness, travel, and design.$md$),
('lifestyle', 'Lifestyle', $md$Lifestyle is the vaguest shelf in print and these two earn it differently. Monocle covers business, design, and geopolitics for people who travel constantly, and Riposte profiles women doing interesting work without the service-journalism framing.$md$);
